'use client'

import React from 'react'
import { ArrowUpRight, Megaphone, MoreVertical } from 'lucide-react'

interface Campaign {
  id: string
  name: string
  channel: string
  status: 'Active' | 'Paused' | 'Completed'
  spend: string
  revenue: string
  roi: string
}

const campaignsData: Campaign[] = [
  {
    id: 'c1',
    name: 'Q3 Product Hunt Launch',
    channel: 'Product Hunt & Direct',
    status: 'Active',
    spend: '$2,400',
    revenue: '$14,800',
    roi: '+516%',
  },
  {
    id: 'c2',
    name: 'Google Ads — High Intent B2B',
    channel: 'Google Search Ads',
    status: 'Active',
    spend: '$6,500',
    revenue: '$28,450',
    roi: '+337%',
  },
  {
    id: 'c3',
    name: 'LinkedIn Sponsored Content',
    channel: 'LinkedIn Paid',
    status: 'Active',
    spend: '$4,200',
    revenue: '$11,900',
    roi: '+183%',
  },
  {
    id: 'c4',
    name: 'Founder Retargeting Newsletter',
    channel: 'Email Sequence',
    status: 'Paused',
    spend: '$450',
    revenue: '$4,120',
    roi: '+815%',
  },
]

export function CampaignsTable() {
  return (
    <div className="p-6 rounded-xl bg-[#0a0a0a] border border-white/[0.07] space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-base font-bold text-white tracking-tight">
            Top Performing Campaigns
          </h3>
          <p className="text-xs text-gray-400 mt-1">
            Real-time ROI, acquisition cost, and revenue generated by marketing channel.
          </p>
        </div>
        <button
          type="button"
          className="text-xs font-mono text-[#5e84fc] hover:underline cursor-pointer"
        >
          View all campaigns →
        </button>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs">
          <thead>
            <tr className="border-b border-white/[0.06] text-gray-400 font-mono text-[11px] uppercase tracking-wider">
              <th className="pb-3 pr-4 font-semibold">Campaign Name</th>
              <th className="pb-3 px-3 font-semibold">Status</th>
              <th className="pb-3 px-3 text-right font-semibold">Ad Spend</th>
              <th className="pb-3 px-3 text-right font-semibold">Revenue</th>
              <th className="pb-3 pl-3 text-right font-semibold">Net ROI</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/[0.05]">
            {campaignsData.map((c) => (
              <tr key={c.id} className="hover:bg-white/[0.03] transition-colors">
                <td className="py-3.5 pr-4">
                  <div className="font-semibold text-white">{c.name}</div>
                  <div className="text-[11px] text-gray-400 mt-0.5">{c.channel}</div>
                </td>
                <td className="py-3.5 px-3">
                  <span
                    className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10.5px] font-semibold font-mono ${
                      c.status === 'Active'
                        ? 'bg-[#22c55e]/15 text-[#22c55e] border border-[#22c55e]/30'
                        : 'bg-gray-500/15 text-gray-400 border border-gray-500/30'
                    }`}
                  >
                    <span
                      className={`size-1.5 rounded-full ${
                        c.status === 'Active' ? 'bg-[#22c55e]' : 'bg-gray-400'
                      }`}
                    />
                    {c.status}
                  </span>
                </td>
                <td className="py-3.5 px-3 text-right font-mono text-gray-300">
                  {c.spend}
                </td>
                <td className="py-3.5 px-3 text-right font-mono font-bold text-white">
                  {c.revenue}
                </td>
                <td className="py-3.5 pl-3 text-right font-mono font-bold text-[#22c55e]">
                  {c.roi}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
